enum custom_keycodes {
    DBL_SPACE = SAFE_RANGE,
    CLICK_THIS_SPOT,
    TOGGLE_VIM,
    WORKSPACE_LEFT,
    WORKSPACE_RIGHT,
    POWERSCROLL_UP,
    POWERSCROLL_DOWN,
    TO_DEFAULT_LAYER,
    TOGGLE_MAC,
    TOGGLE_COLEMAK
};
