# BOARD = GENERIC_RP_RP2040
# CONVERT_TO = promicro_rp2040
SPLIT_KEYBOARD = yes
BOOTLOADER = rp2040
# MCU = RP2040
SERIAL_DRIVER = vendor

# SERIAL_DRIVER = vendor

# CONSOLE_ENABLE = yes

# OS_DETECTION_ENABLE = yes

# ENCODER_ENABLE = yes

# SPLIT_KEYBOARD = yes
# USE_SERIAL = yes
# SOFT_SERIAL_ENABLE = yes
# SOFT_SERIAL_PIN = GP0
# SERIAL_USE_MULTI_TRANSACTION = no


# SERIAL_USART_HALF_DUPLEX = yes
SERIAL_USART_FULL_DUPLEX = yes

