# VIA_ENABLE = yes
# BOARD = GENERIC_RP_RP2040
SERIAL_DRIVER = vendor

CONSOLE_ENABLE = yes

OS_DETECTION_ENABLE = yes

# ENCODER_ENABLE = yes

# SPLIT_KEYBOARD = yes
# USE_SERIAL = yes
# SOFT_SERIAL_ENABLE = no
# SERIAL_USE_MULTI_TRANSACTION = no
#

# SERIAL_USART_HALF_DUPLEX = yes
SERIAL_USART_FULL_DUPLEX = yes

